nome = input("Digite o nome do cliente:")
vencimento = input("Digite o dia do vencimento:")
mes_vencimento = input("Digite o mê de vencimento:")
valor = input("Digite o valor da fatura:")
print("Olá, {}\nA sua fatura com vencimento em {} de {} no valor de R$ {} está fechada.".format(nome, vencimento, mes_vencimento, valor))